#!/usr/bin/env bash

NETWORK_DNS_RESOLV="${KEINE_RESOLV_CONF:-/etc/resolv.conf}"
NETWORK_DNS_DROPIN="${KEINE_DNS_DROPIN:-/etc/systemd/resolved.conf.d/90-keine-dns.conf}"
NETWORK_DNS_HEAD="${KEINE_RESOLVCONF_HEAD:-/etc/resolvconf/resolv.conf.d/head}"
NETWORK_DNS_CHECK_HOST="example.com"

network_dns_backend() {
  local target
  target="$(readlink -f -- "$NETWORK_DNS_RESOLV" 2>/dev/null || true)"
  if [[ "$target" == /run/systemd/resolve/* ]] && command_exists resolvectl &&
    systemctl is-active --quiet systemd-resolved.service; then
    printf resolved
  elif command_exists resolvconf && { [[ "$target" == /run/resolvconf/* ]] || grep -qi 'generated by.*resolvconf' "$NETWORK_DNS_RESOLV" 2>/dev/null; }; then
    printf resolvconf
  elif [[ ! -L "$NETWORK_DNS_RESOLV" ]] && ! grep -qiE 'generated by|NetworkManager|resolvconf|systemd-resolved|cloud-init' "$NETWORK_DNS_RESOLV" 2>/dev/null; then
    if command_exists systemctl && systemctl is-active --quiet NetworkManager.service; then printf unmanaged; else printf plain; fi
  else printf unmanaged; fi
}

network_dns_path() {
  case "$(network_dns_backend)" in
    resolved) printf '%s' "$NETWORK_DNS_DROPIN" ;; resolvconf) printf '%s' "$NETWORK_DNS_HEAD" ;;
    plain) printf '%s' "$NETWORK_DNS_RESOLV" ;; *) return 1 ;;
  esac
}

network_dns_addresses() {
  local text="${1:-}" address
  local dns_addresses=()
  [[ "$text" != *$'\n'* && "$text" != *$'\r'* ]] || return 1
  text="${text//,/ }"
  IFS=$' \t' read -r -a dns_addresses <<<"$text"
  (( ${#dns_addresses[@]} >= 1 && ${#dns_addresses[@]} <= 3 )) || return 1
  for address in "${dns_addresses[@]}"; do
    if ! valid_ipv4_address "$address" && ! valid_ipv6_address "$address"; then return 1; fi
    [[ "$address" != 0.0.0.0 && "$address" != :: ]] || return 1
  done
  printf '%s\n' "${dns_addresses[@]}"
}

network_dns_reload() {
  case "${NETWORK_DNS_ACTIVE_BACKEND:-$(network_dns_backend)}" in
    resolved) run systemctl restart systemd-resolved.service ;;
    resolvconf) run resolvconf -u ;;
    plain) return 0 ;;
    *) warn "当前解析器不是可安全应用的后端。"; return 1 ;;
  esac
}

network_dns_verify() {
  network_dns_reload || return 1
  getent ahosts "$NETWORK_DNS_CHECK_HOST" >/dev/null 2>&1 || {
    warn "解析验证失败：$NETWORK_DNS_CHECK_HOST"; return 1;
  }
}

network_dns_payload() {
  local backend="$1" path="$2" addresses="$3" address joined
  case "$backend" in
    resolved)
      joined="${addresses//$'\n'/ }"
      printf '# Managed by keine\n[Resolve]\nDNS=\nDNS=%s\nFallbackDNS=\nDomains=~.\n' "$joined"
      ;;
    plain)
      printf '# Managed by keine DNS\n'
      if [[ -f "$path" ]]; then awk '!/^[[:space:]]*nameserver[[:space:]]/ && $0 != "# Managed by keine DNS" {print}' "$path"; fi
      while IFS= read -r address; do printf 'nameserver %s\n' "$address"; done <<<"$addresses"
      ;;
    resolvconf)
      if [[ -f "$path" ]]; then
        awk '$0 == "# BEGIN keine DNS" {block=1; next} $0 == "# END keine DNS" {block=0; next} !block {print}' "$path"
      fi
      printf '# BEGIN keine DNS\n'
      while IFS= read -r address; do printf 'nameserver %s\n' "$address"; done <<<"$addresses"
      printf '# END keine DNS\n'
      ;;
  esac
}

network_dns_configure() {
  local choice input addresses backend path payload host
  local NETWORK_DNS_ACTIVE_BACKEND
  backend="$(network_dns_backend)"
  NETWORK_DNS_ACTIVE_BACKEND="$backend"
  path="$(network_dns_path)" || { warn "解析器由其他组件管理；请在 NetworkManager、Netplan 或服务商配置中修改，不覆盖其生成文件。"; return 1; }
  if [[ "$backend" == resolved && -e "$path" && ! -d "$(changes_file_entry "$path")" ]] &&
    ! config_project_marker "$path"; then warn "该 drop-in 已存在且没有项目归属，拒绝覆盖。"; return 1; fi
  ui_page "DNS 配置 / 选择服务器" "配置系统解析器；不会修改 Xray / sing-box 的内部 DNS"
  ui_action 1 "Cloudflare" "action" "1.1.1.1 / 1.0.0.1"
  ui_action 2 "Quad9" "action" "9.9.9.9 / 149.112.112.112"
  ui_action 3 "Google Public DNS" "action" "8.8.8.8 / 8.8.4.4"
  ui_action 4 "自定义" "accent" "IPv4 / IPv6，最多 3 个，逗号或空格分隔"
  ui_action 0 "返回" "muted"
  choice="$(read_input "请选择" "0")"
  case "$choice" in
    1) input='1.1.1.1,1.0.0.1' ;; 2) input='9.9.9.9,149.112.112.112' ;; 3) input='8.8.8.8,8.8.4.4' ;;
    4) input="$(read_input "DNS 地址" "")" ;; *) return 0 ;;
  esac
  addresses="$(network_dns_addresses "$input")" || { warn "DNS 地址格式无效；仅接受最多 3 个 IPv4 / IPv6 地址。"; return 1; }
  host="$(read_input "验证解析的域名" "example.com")"
  [[ "$host" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]{0,252}$ && "$host" != *..* && "$host" == *.* && "$host" == *[a-zA-Z]* ]] || {
    warn "验证目标须为域名，例如 example.com，不能使用 IP 地址。"; return 1;
  }
  NETWORK_DNS_CHECK_HOST="$host"
  ui_kv "后端" "$backend"; ui_kv "目标文件" "$path"; ui_kv "DNS" "${addresses//$'\n'/ · }"
  ui_hint "先保留服务商控制台；resolved 会短暂重启解析服务，VPN 更具体的 DNS 路由仍可能优先。验证失败会回退。"
  confirm "保存并应用上述系统 DNS？" || return 0
  payload="$(network_dns_payload "$backend" "$path" "$addresses")" || return 1
  config_file_write "$path" 0644 "$payload" network_dns_verify || return 1
  audit "action=network-dns-configure backend=$backend"
  ui_success "DNS 配置操作完成。"
}

network_dns_restore_path() {
  local path="$1" expected
  local NETWORK_DNS_ACTIVE_BACKEND
  NETWORK_DNS_ACTIVE_BACKEND="$(network_dns_backend)"
  expected="$(network_dns_path)" || return 1
  [[ "$expected" == "$path" ]] || { warn "DNS 后端已改变，保留原始记录；请先检查当前网络管理器。"; return 1; }
  config_file_restore "$path" network_dns_verify
}

network_dns_restore() {
  local path
  path="$(network_dns_path)" || { warn "当前解析器后端发生变化；请先在恢复与撤销中心检查原始记录。"; return 1; }
  confirm "恢复该解析器首次项目修改前的配置，并重新验证？" || return 0
  network_dns_restore_path "$path" || return 1
  audit 'action=network-dns-restore'
  ui_success "系统 DNS 已恢复初始配置。"
}

network_dns_menu() {
  local choice backend path
  while true; do
    backend="$(network_dns_backend)"; path="$(network_dns_path || true)"
    ui_page "系统 DNS 配置" "原生后端识别、服务器切换、解析验证与恢复"
    ui_panel_begin "当前解析器"
    ui_panel_kv "后端" "$backend"
    ui_panel_kv "配置文件" "${path:-由其他网络管理器控制}"
    ui_panel_end
    sed -n '/^nameserver[[:space:]]/p' "$NETWORK_DNS_RESOLV" 2>/dev/null || true
    ui_note "只调整主机系统 DNS；不锁定 resolv.conf，也不禁用现有网络管理器。"
    ui_action 1 "配置 DNS" "action" "公共解析器或自定义地址"
    ui_action 2 "解析诊断" "action" "检查当前生效路径与 DNS 记录"
    ui_action 3 "恢复初始配置" "warning" "保留外部修改冲突，不强行覆盖"
    ui_action 0 "返回" "muted"
    choice="$(read_input "请选择" "0")"
    case "$choice" in 1) network_dns_configure || true ;; 2) network_dns_diagnose ;; 3) network_dns_restore || true ;; 0) return 0 ;; *) warn "未知选项"; continue ;; esac
    pause
  done
}
